export type ThemeGroupStatus = "implemented" | "planned";
export type ClassificationMethod = "rule" | "llm" | "manual" | "unknown";

export type ThemeGroup = {
  slug: string;
  name: string;
  status: ThemeGroupStatus;
  description: string;
  sortOrder: number;
};

export type ThemeSubTheme = {
  slug: string;
  themeGroupSlug: string;
  name: string;
  status: ThemeGroupStatus;
  keywords: string[];
  seedSymbols: string[];
  description: string;
  references: Array<{
    label: string;
    url: string;
  }>;
  sortOrder: number;
};

export type SectorMapping = {
  sector: string;
  subCategory: string;
  slug: string;
  fmpIndustries: string[];
  notes?: string;
};

export const themeGroups: ThemeGroup[] = [
  {
    slug: "ai_data_center",
    name: "AI & Data Center",
    status: "implemented",
    description: "AI infrastructure, accelerators, cloud capacity, and data center demand.",
    sortOrder: 10,
  },
  {
    slug: "crypto_digital_assets",
    name: "Crypto & Digital Assets",
    status: "implemented",
    description: "Crypto infrastructure, digital asset balance sheets, exchanges, miners, and tokens.",
    sortOrder: 20,
  },
  {
    slug: "healthcare_momentum",
    name: "Healthcare Momentum",
    status: "implemented",
    description: "Clinical catalysts, drug approvals, medical devices, and healthcare deal flow.",
    sortOrder: 30,
  },
  {
    slug: "power_energy_resources",
    name: "Power, Energy & Resources",
    status: "planned",
    description: "Power demand, nuclear, uranium, LNG, oil and gas, renewables, and key resources.",
    sortOrder: 40,
  },
  {
    slug: "defense_geopolitics",
    name: "Defense & Geopolitics",
    status: "planned",
    description: "Defense contractors, aerospace programs, sanctions, conflict, and geopolitical policy.",
    sortOrder: 50,
  },
  {
    slug: "rates_credit_banks",
    name: "Rates, Credit & Banks",
    status: "planned",
    description: "Banks, credit stress, yields, lending, capital markets, and rate-sensitive moves.",
    sortOrder: 60,
  },
  {
    slug: "retail_momentum_flows",
    name: "Retail & Momentum Flows",
    status: "planned",
    description: "High-volume retail names, squeezes, social momentum, and flow-driven setups.",
    sortOrder: 70,
  },
  {
    slug: "policy_regulation",
    name: "Policy & Regulation",
    status: "planned",
    description: "Regulatory, agency, court, White House, and enforcement actions with market impact.",
    sortOrder: 80,
  },
];

export const themeSubThemes: ThemeSubTheme[] = [
  subTheme(
    "ai_data_center",
    "ai_infrastructure",
    "AI Infrastructure",
    [
      "AI factory",
      "accelerated computing",
      "GPU cluster",
      "AI server",
      "rack-scale architecture",
      "liquid cooling",
      "optical interconnect",
      "InfiniBand",
      "Ethernet",
      "NVLink",
      "DPU",
      "power/cooling",
      "sovereign AI",
    ],
    ["NVDA", "AMD", "AVGO", "MRVL", "ANET", "DELL", "SMCI", "VRT", "ETN", "CLS"],
    "Full-stack infrastructure for AI training and inference, including compute, networking, storage, power, and cooling at rack or data-center scale.",
    [{ label: "NVIDIA Data Center", url: "https://www.nvidia.com/en-us/data-center/" }],
    10,
  ),
  subTheme(
    "ai_data_center",
    "ai_data_centers",
    "AI Data Centers",
    [
      "hyperscale data center",
      "colocation",
      "neocloud",
      "GPU cloud",
      "AI cloud",
      "data center REIT",
      "leased GPU capacity",
      "power-backed campus",
      "sovereign cloud",
      "AI hosting",
    ],
    ["EQIX", "DLR", "CRWV", "NBIS", "IREN", "AMZN", "MSFT", "GOOGL", "ORCL"],
    "Physical data-center, colocation, REIT, and GPU-cloud operators that provide large-scale AI compute capacity.",
    [
      { label: "CoreWeave Investor Relations", url: "https://investors.coreweave.com/overview/default.aspx" },
    ],
    20,
  ),
  subTheme(
    "ai_data_center",
    "ai_chips_hbm",
    "AI Chips & HBM",
    [
      "GPU",
      "AI accelerator",
      "custom ASIC",
      "HBM3E",
      "HBM4",
      "HBM4E",
      "CoWoS",
      "advanced packaging",
      "chiplet",
      "interposer",
      "memory bandwidth",
      "server DRAM",
      "CXL",
    ],
    ["NVDA", "AMD", "AVGO", "MRVL", "TSM", "ASML", "AMAT", "LRCX", "MU"],
    "AI compute supply chain focused on accelerators, high-bandwidth memory, advanced packaging, and memory bandwidth bottlenecks.",
    [{ label: "Micron HBM4", url: "https://www.micron.com/products/memory/hbm/hbm4" }],
    30,
  ),
  subTheme(
    "ai_data_center",
    "ai_software_agents",
    "AI Software Agents",
    [
      "AI agent",
      "agentic AI",
      "Copilot",
      "autonomous workflow",
      "tool calling",
      "RAG",
      "reasoning model",
      "inference token",
      "multi-step task",
      "workflow automation",
      "enterprise AI",
    ],
    ["MSFT", "GOOGL", "AMZN", "META", "CRM", "NOW", "PLTR", "SNOW", "ORCL", "ADBE"],
    "Software and platform layer that can indirectly increase inference demand through agents, tool use, retrieval, and enterprise workflow automation.",
    [{ label: "OpenAI Agents Tools", url: "https://openai.com/index/new-tools-for-building-agents/" }],
    40,
  ),
  subTheme(
    "ai_data_center",
    "cloud_capex",
    "Cloud Capex",
    [
      "hyperscaler capex",
      "AI capex",
      "cloud infrastructure buildout",
      "GPU procurement",
      "finance lease",
      "technical infrastructure",
      "server capex",
      "data center backlog",
      "AI cluster expansion",
    ],
    ["MSFT", "AMZN", "GOOGL", "META", "ORCL", "CRWV", "NBIS"],
    "Hyperscaler and AI-cloud investment cycle, with capex and lease commitments driving infrastructure demand.",
    [
      {
        label: "Microsoft FY2026 Q3 Earnings",
        url: "https://www.microsoft.com/en-us/investor/events/fy-2026/earnings-fy-2026-q3",
      },
    ],
    50,
  ),
  subTheme(
    "ai_data_center",
    "data_center_power_demand",
    "Data Center Power Demand",
    [
      "electricity demand",
      "grid interconnection",
      "power purchase agreement",
      "PPA",
      "nuclear power",
      "gas turbine",
      "renewables",
      "substation",
      "transformer",
      "UPS",
      "backup power",
      "cooling",
      "water usage",
    ],
    ["CEG", "VST", "NEE", "SO", "DUK", "D", "ETR", "GEV", "ETN", "PWR", "TT", "BE"],
    "Power, grid, cooling, and equipment demand tied to AI data-center expansion and interconnection constraints.",
    [
      {
        label: "IEA Energy and AI",
        url: "https://www.iea.org/reports/key-questions-on-energy-and-ai/executive-summary",
      },
    ],
    60,
  ),
  subTheme(
    "crypto_digital_assets",
    "bitcoin",
    "Bitcoin",
    [
      "Bitcoin",
      "BTC treasury",
      "digital gold",
      "spot crypto exposure",
      "crypto custody",
      "wallets",
      "exchange volume",
      "institutional adoption",
      "Bitcoin futures",
      "Bitcoin options",
      "corporate treasury strategy",
    ],
    ["MSTR", "COIN", "HOOD", "XYZ", "CME"],
    "Companies with direct or indirect sensitivity to Bitcoin adoption, trading activity, custody demand, derivatives activity, or balance-sheet Bitcoin exposure.",
    [
      {
        label: "Strategy Investor Relations",
        url: "https://www.strategy.com/press/strategy-announces-first-quarter-2026-financial-results_05-05-2026",
      },
    ],
    110,
  ),
  subTheme(
    "crypto_digital_assets",
    "stablecoins",
    "Stablecoins",
    [
      "USDC",
      "PYUSD",
      "payment stablecoins",
      "dollar-backed tokens",
      "reserve income",
      "tokenized cash",
      "on-chain settlement",
      "cross-border payments",
      "merchant settlement",
      "stablecoin regulation",
    ],
    ["CRCL", "COIN", "PYPL", "V", "MA"],
    "Dollar-backed digital money and payment rails, including stablecoin issuers, exchanges, payment networks, and settlement infrastructure.",
    [
      {
        label: "Reuters Circle Stablecoin Demand",
        url: "https://www.reuters.com/technology/circles-quarterly-earnings-benefit-stablecoin-safety-during-volatile-period-2026-05-11/",
      },
    ],
    120,
  ),
  subTheme(
    "crypto_digital_assets",
    "tokenization",
    "Tokenization",
    [
      "RWA",
      "tokenized Treasuries",
      "tokenized money-market funds",
      "tokenized stocks",
      "digital transfer agent",
      "on-chain NAV",
      "programmable settlement",
      "deposit tokens",
      "tokenized collateral",
      "blockchain settlement",
    ],
    ["BLK", "JPM", "BEN", "HOOD", "ICE", "BK", "GS", "COIN"],
    "Traditional financial assets moving onto blockchain rails, including tokenized funds, Treasuries, equities, deposit tokens, custody, and settlement infrastructure.",
    [
      {
        label: "Franklin Templeton BENJI",
        url: "https://www.franklintempleton.com/press-releases/news-room/2026/franklin-templeton-stellar-development-foundation-mark-five-years-of-benji-the-first-u.s.-registered-tokenized-money-market-fund",
      },
    ],
    130,
  ),
  subTheme(
    "crypto_digital_assets",
    "crypto_regulation",
    "Crypto Regulation",
    [
      "GENIUS Act",
      "CLARITY Act",
      "SEC/CFTC jurisdiction",
      "market structure",
      "token classification",
      "custody rules",
      "broker-dealer rules",
      "AML/KYC",
      "stablecoin reserves",
      "spot crypto products",
    ],
    ["COIN", "HOOD", "CRCL", "PYPL", "CME", "ICE", "NDAQ", "BLK"],
    "Companies exposed to policy changes around crypto market structure, token classification, custody, stablecoin issuance, regulated products, and exchange oversight.",
    [
      {
        label: "SEC Crypto Task Force",
        url: "https://www.sec.gov/featured-topics/crypto-task-force",
      },
    ],
    140,
  ),
  subTheme(
    "crypto_digital_assets",
    "crypto_mining",
    "Crypto Mining",
    [
      "Bitcoin mining",
      "hashrate",
      "ASIC miners",
      "block rewards",
      "transaction fees",
      "mining difficulty",
      "power cost",
      "energy contracts",
      "curtailment",
      "mining pools",
      "halving",
      "HPC pivot",
      "AI data center pivot",
    ],
    ["MARA", "RIOT", "CLSK", "IREN", "CORZ", "CIFR", "WULF", "HUT"],
    "Public miners and digital-infrastructure companies exposed to Bitcoin price, mining difficulty, power costs, site control, and the pivot toward HPC or AI data-center hosting.",
    [{ label: "MARA Investor Relations", url: "https://ir.mara.com/" }],
    150,
  ),
  subTheme(
    "healthcare_momentum",
    "glp1_obesity_drugs",
    "GLP-1 & Obesity Drugs",
    [
      "GLP-1",
      "GIP/GLP-1",
      "incretin therapy",
      "tirzepatide",
      "semaglutide",
      "oral GLP-1",
      "obesity",
      "weight management",
      "cardiometabolic disease",
      "obstructive sleep apnea",
      "MASH",
      "NASH",
      "supply expansion",
      "compounding risk",
    ],
    ["LLY", "NVO", "AMGN", "VKTX", "GPCR", "ALT", "HIMS"],
    "Companies exposed to obesity, cardiometabolic, and related incretin drug cycles, including GLP-1, GIP/GLP-1, oral obesity drugs, supply expansion, and compounding-risk catalysts.",
    [
      {
        label: "FDA Chronic Weight Management Approval",
        url: "https://www.fda.gov/news-events/press-announcements/fda-approves-new-medication-chronic-weight-management",
      },
    ],
    210,
  ),
  subTheme(
    "healthcare_momentum",
    "oncology_breakthroughs",
    "Oncology Breakthroughs",
    [
      "antibody-drug conjugates",
      "ADCs",
      "bispecific antibodies",
      "T-cell engagers",
      "CAR-T",
      "TIL therapy",
      "radioligand therapy",
      "KRAS",
      "PD-1",
      "PD-L1",
      "tumor-agnostic therapy",
      "companion diagnostics",
      "precision oncology",
    ],
    ["MRK", "AMGN", "PFE", "BMY", "GILD", "REGN", "ABBV", "IOVA", "VSTM"],
    "Next-generation oncology treatments and diagnostics, including ADCs, bispecifics, cell therapies, radioligands, biomarker-selected drugs, and precision-oncology approval catalysts.",
    [
      {
        label: "FDA Oncology Approval Notifications",
        url: "https://www.fda.gov/drugs/resources-information-approved-drugs/oncology-cancerhematologic-malignancies-approval-notifications",
      },
    ],
    220,
  ),
  subTheme(
    "healthcare_momentum",
    "gene_editing",
    "Gene Editing",
    [
      "CRISPR/Cas9",
      "base editing",
      "prime editing",
      "in vivo editing",
      "ex vivo editing",
      "one-time therapy",
      "LNP delivery",
      "AAV delivery",
      "hematopoietic stem cells",
      "BCL11A",
      "off-target risk",
      "genetic medicine",
    ],
    ["CRSP", "VRTX", "NTLA", "BEAM", "EDIT", "PRME", "LLY", "REGN"],
    "Gene-editing and genetic-medicine companies using CRISPR, base editing, prime editing, in vivo or ex vivo delivery, and one-time therapy approaches.",
    [
      {
        label: "FDA First CRISPR Gene Therapies",
        url: "https://www.fda.gov/news-events/press-announcements/fda-approves-first-gene-therapies-treat-patients-sickle-cell-disease",
      },
    ],
    230,
  ),
  subTheme(
    "healthcare_momentum",
    "rare_disease_drugs",
    "Rare Disease Drugs",
    [
      "orphan drug",
      "ultra-rare disease",
      "genetic disease",
      "RNAi",
      "antisense oligonucleotide",
      "gene therapy",
      "enzyme replacement therapy",
      "Duchenne muscular dystrophy",
      "cystic fibrosis",
      "ATTR amyloidosis",
      "hereditary angioedema",
      "priority review",
      "accelerated approval",
    ],
    ["VRTX", "ALNY", "RARE", "IONS", "SRPT", "BMRN", "FOLD", "MIRM"],
    "Companies developing therapies for rare or ultra-rare diseases where orphan designation, priority review, accelerated approval, genetic targeting, and pricing power can drive catalysts.",
    [
      {
        label: "FDA New Drug Therapy Approvals 2025",
        url: "https://www.fda.gov/media/190705/download",
      },
    ],
    240,
  ),
  subTheme(
    "healthcare_momentum",
    "medical_ai_diagnostics",
    "Medical AI & Diagnostics",
    [
      "AI-enabled medical devices",
      "SaMD",
      "radiology AI",
      "pathology AI",
      "digital pathology",
      "clinical decision support",
      "companion diagnostics",
      "liquid biopsy",
      "NGS",
      "multi-cancer early detection",
      "precision medicine",
      "FDA 510(k)",
      "workflow automation",
    ],
    ["TEM", "GEHC", "ABT", "GH", "NTRA", "HOLX", "TMO", "DGX", "LH", "A"],
    "Diagnostics, imaging, genomics, and AI-enabled medical-device companies exposed to FDA-cleared software, clinical workflow automation, liquid biopsy, NGS, and precision medicine.",
    [
      {
        label: "FDA AI-Enabled Medical Devices",
        url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-enabled-medical-devices",
      },
    ],
    250,
  ),
];

export const sectorMappings: SectorMapping[] = [
  map("Technology", "Semiconductors & Compute", "semiconductors_compute", ["Semiconductors"]),
  map("Technology", "Software & Cloud", "software_cloud", [
    "Software - Services",
    "Software - Infrastructure",
    "Software - Application",
  ]),
  map("Technology", "Cybersecurity", "cybersecurity", [], "Theme or manual list; FMP has no stable direct industry."),
  map("Technology", "IT Services", "it_services", ["Information Technology Services"]),
  map("Technology", "Hardware & Electronics", "hardware_electronics", [
    "Hardware, Equipment & Parts",
    "Computer Hardware",
    "Consumer Electronics",
    "Communication Equipment",
    "Technology Distributors",
  ]),
  map("Communication Services", "Internet Platforms", "internet_platforms", [
    "Internet Content & Information",
  ]),
  map("Communication Services", "Media & Entertainment", "media_entertainment", [
    "Media & Entertainment",
    "Entertainment",
    "Broadcasting",
  ]),
  map("Communication Services", "Gaming", "gaming", ["Electronic Gaming & Multimedia"]),
  map("Communication Services", "Telecom & Connectivity", "telecom_connectivity", [
    "Telecommunications Services",
  ]),
  map("Communication Services", "Advertising & Information Services", "advertising_information_services", [
    "Advertising Agencies",
    "Publishing",
  ]),
  map("Consumer Cyclical", "Autos & Mobility", "autos_mobility", [
    "Auto - Manufacturers",
    "Auto - Parts",
    "Auto - Recreational Vehicles",
    "Auto - Dealerships",
  ]),
  map("Consumer Cyclical", "Retail & E-commerce", "retail_ecommerce", [
    "Specialty Retail",
    "Department Stores",
  ]),
  map("Consumer Cyclical", "Restaurants", "restaurants", ["Restaurants"]),
  map("Consumer Cyclical", "Travel & Leisure", "travel_leisure", [
    "Travel Lodging",
    "Travel Services",
    "Leisure",
    "Gambling",
    "Resorts & Casinos",
  ]),
  map("Consumer Cyclical", "Home & Lifestyle", "home_lifestyle", [
    "Home Improvement",
    "Residential Construction",
    "Furnishings, Fixtures & Appliances",
  ]),
  map("Consumer Cyclical", "Apparel & Luxury", "apparel_luxury", [
    "Apparel - Retail",
    "Apparel - Manufacturers",
    "Apparel - Footwear & Accessories",
    "Luxury Goods",
  ]),
  map("Consumer Defensive", "Food & Beverage", "food_beverage", [
    "Packaged Foods",
    "Food Distribution",
    "Food Confectioners",
    "Beverages - Non-Alcoholic",
    "Beverages - Alcoholic",
    "Beverages - Wineries & Distilleries",
  ]),
  map("Consumer Defensive", "Household & Personal Care", "household_personal_care", [
    "Household & Personal Products",
    "Personal Products & Services",
  ]),
  map("Consumer Defensive", "Grocery & Discount Retail", "grocery_discount_retail", [
    "Grocery Stores",
    "Discount Stores",
  ]),
  map("Consumer Defensive", "Agriculture & Staples", "agriculture_staples", [
    "Agricultural Farm Products",
  ]),
  map("Consumer Defensive", "Tobacco, Cannabis & Alternative Products", "tobacco_cannabis_alternatives", [
    "Tobacco",
  ]),
  map("Healthcare", "Biotechnology", "biotechnology", ["Biotechnology"]),
  map("Healthcare", "Pharmaceuticals", "pharmaceuticals", [
    "Medical - Pharmaceuticals",
    "Drug Manufacturers - General",
    "Drug Manufacturers - Specialty & Generic",
  ]),
  map("Healthcare", "Medical Devices & Diagnostics", "medical_devices_diagnostics", [
    "Medical - Devices",
    "Medical - Instruments & Supplies",
    "Medical - Diagnostics & Research",
    "Medical - Equipment & Services",
  ]),
  map("Healthcare", "Healthcare Services", "healthcare_services", [
    "Medical - Care Facilities",
    "Medical - Distribution",
    "Medical - Healthcare Information Services",
    "Medical - Specialties",
  ]),
  map("Healthcare", "Health Insurance & Managed Care", "health_insurance_managed_care", [
    "Medical - Healthcare Plans",
  ]),
  map("Financial Services", "Banks", "banks", [
    "Banks",
    "Banks - Diversified",
    "Banks - Regional",
  ]),
  map("Financial Services", "Capital Markets & Exchanges", "capital_markets_exchanges", [
    "Financial - Capital Markets",
    "Financial - Data & Stock Exchanges",
    "Investment - Banking & Investment Services",
  ]),
  map("Financial Services", "Insurance", "insurance", [
    "Insurance - Specialty",
    "Insurance - Reinsurance",
    "Insurance - Property & Casualty",
    "Insurance - Life",
    "Insurance - Diversified",
    "Insurance - Brokers",
  ]),
  map("Financial Services", "Asset & Wealth Management", "asset_wealth_management", [
    "Asset Management",
    "Asset Management - Bonds",
    "Asset Management - Income",
    "Asset Management - Leveraged",
    "Asset Management - Global",
  ]),
  map("Financial Services", "Payments & Lending", "payments_lending", [
    "Financial - Credit Services",
    "Financial - Mortgages",
  ]),
  map("Financial Services", "Fintech & Digital Assets", "fintech_digital_assets", [
    "Asset Management - Cryptocurrency",
  ], "Theme membership should supplement this because the FMP industry is narrow."),
  map("Financial Services", "Diversified Finance", "diversified_finance", [
    "Financial - Diversified",
    "Financial - Conglomerates",
  ]),
  map("Industrials", "Aerospace & Defense", "aerospace_defense", ["Aerospace & Defense"]),
  map("Industrials", "Machinery & Equipment", "machinery_equipment", [
    "Industrial - Machinery",
    "Agricultural - Machinery",
    "Electrical Equipment & Parts",
    "Manufacturing - Tools & Accessories",
  ]),
  map("Industrials", "Transportation & Logistics", "transportation_logistics", [
    "General Transportation",
    "Integrated Freight & Logistics",
    "Railroads",
    "Trucking",
    "Marine Shipping",
    "Airlines",
    "Airports & Air Services",
  ]),
  map("Industrials", "Construction & Infrastructure", "construction_infrastructure", [
    "Construction",
    "Engineering & Construction",
    "Industrial - Infrastructure Operations",
  ]),
  map("Industrials", "Industrial Services & Manufacturing", "industrial_services_manufacturing", [
    "Manufacturing - Miscellaneous",
    "Manufacturing - Metal Fabrication",
    "Manufacturing - Textiles",
    "Industrial - Distribution",
    "Industrial - Specialties",
    "Industrial - Capital Goods",
    "Business Equipment & Supplies",
  ]),
  map("Industrials", "Environmental & Waste", "environmental_waste", [
    "Waste Management",
    "Environmental Services",
    "Industrial - Pollution & Treatment Controls",
  ]),
  map("Industrials", "Business Services", "business_services", [
    "Consulting Services",
    "Staffing & Employment Services",
    "Rental & Leasing Services",
    "Security & Protection Services",
    "Specialty Business Services",
  ]),
  map("Industrials", "Conglomerates", "conglomerates", ["Conglomerates"]),
  map("Energy", "Oil, Gas & Refining", "oil_gas_refining", [
    "Oil & Gas Integrated",
    "Oil & Gas Exploration & Production",
    "Oil & Gas Refining & Marketing",
    "Oil & Gas Energy",
  ]),
  map("Energy", "Midstream & LNG", "midstream_lng", ["Oil & Gas Midstream"]),
  map("Energy", "Energy Services & Equipment", "energy_services_equipment", [
    "Oil & Gas Equipment & Services",
    "Oil & Gas Drilling",
  ]),
  map("Energy", "Renewable Energy", "renewable_energy", ["Solar"], "Theme membership should cover non-solar renewables."),
  map("Energy", "Nuclear & Uranium", "nuclear_uranium", ["Uranium"]),
  map("Energy", "Coal", "coal", ["Coal"]),
  map("Utilities", "Electric Utilities", "electric_utilities", ["Regulated Electric"]),
  map("Utilities", "Power Generation & Grid", "power_generation_grid", [
    "Independent Power Producers",
  ]),
  map("Utilities", "Water & Multi-Utilities", "water_multi_utilities", [
    "Regulated Water",
    "Diversified Utilities",
    "General Utilities",
    "Renewable Utilities",
  ]),
  map("Utilities", "Gas Utilities", "gas_utilities", ["Regulated Gas"]),
  map("Basic Materials", "Metals & Mining", "metals_mining", [
    "Steel",
    "Copper",
    "Aluminum",
    "Industrial Materials",
  ]),
  map("Basic Materials", "Precious Metals", "precious_metals", [
    "Gold",
    "Silver",
    "Other Precious Metals",
  ]),
  map("Basic Materials", "Chemicals", "chemicals", ["Chemicals", "Chemicals - Specialty"]),
  map("Basic Materials", "Agricultural Inputs", "agricultural_inputs", [
    "Agricultural Inputs",
    "Agricultural - Commodities/Milling",
  ]),
  map("Basic Materials", "Packaging & Materials", "packaging_materials", [
    "Paper",
    "Lumber & Forest Products",
    "Packaging & Containers",
    "Construction Materials",
  ]),
  map("Real Estate", "REITs", "reits", [
    "REIT - Specialty",
    "REIT - Retail",
    "REIT - Residential",
    "REIT - Office",
    "REIT - Mortgage",
    "REIT - Industrial",
    "REIT - Hotel & Motel",
    "REIT - Healthcare Facilities",
    "REIT - Diversified",
  ]),
  map("Real Estate", "Residential Real Estate", "residential_real_estate", [
    "Real Estate - Development",
    "Real Estate - General",
  ]),
  map("Real Estate", "Commercial Real Estate", "commercial_real_estate", [
    "Real Estate - Diversified",
  ]),
  map("Real Estate", "Industrial & Logistics Real Estate", "industrial_logistics_real_estate", [
    "REIT - Industrial",
  ], "Duplicate FMP industry with REITs; priority rules decide default mapping."),
  map("Real Estate", "Real Estate Services", "real_estate_services", [
    "Real Estate - Services",
  ]),
  map("Other", "Shell / SPAC / Undefined", "shell_spac_undefined", ["Shell Companies"]),
  map("Other", "ETF / Funds / Government / CEF", "etf_funds_government_cef", [], "Use asset_type or instrument_type, not only FMP industry."),
  map("Other", "Education", "education", ["Education & Training Services"]),
];

export const taxonomyStats = {
  sectors: new Set(sectorMappings.map((item) => item.sector)).size,
  subCategories: sectorMappings.length,
  fmpIndustries: sectorMappings.reduce((count, item) => count + item.fmpIndustries.length, 0),
  themeGroups: themeGroups.length,
  themeSubThemes: themeSubThemes.length,
  implementedThemes: themeGroups.filter((theme) => theme.status === "implemented").length,
  implementedSubThemes: themeSubThemes.filter((theme) => theme.status === "implemented").length,
};

export const taxonomyCanonicalTables = [
  table("tickers", "Master ticker universe hydrated from FMP and other market-data providers.", [
    col("symbol", "text", "Ticker symbol, primary key", true),
    col("name", "text", "Company or instrument name"),
    col("exchange", "text", "Exchange or venue"),
    col("fmp_sector", "text", "Raw FMP sector"),
    col("fmp_industry", "text", "Raw FMP industry"),
    col("asset_type", "text", "stock, etf, cef, spac, adr, warrant, unit, government, unknown"),
    col("market_cap", "numeric", "Latest market cap from provider"),
    col("is_active", "boolean", "Tradable/watchable flag", true),
    col("last_profiled_at", "timestamptz", "Last profile refresh time"),
    col("metadata", "jsonb", "Provider payload and non-secret classification trace"),
  ]),
  table("market_sectors", "Canonical top-level sector list.", [
    col("code", "text", "Stable sector code", true),
    col("name", "text", "Sector display name", true),
    col("sort_order", "integer", "Admin display order", true),
    col("is_active", "boolean", "Visible and usable flag", true),
  ]),
  table("market_sub_categories", "Sector child buckets used by filters and market-moving views. Static ticker lists do not live here; ticker membership comes from ticker_classifications.", [
    col("sector_code", "text", "References market_sectors.code", true),
    col("slug", "text", "Stable sub-category slug", true),
    col("name", "text", "Display name", true),
    col("sort_order", "integer", "Admin display order", true),
    col("is_active", "boolean", "Visible and usable flag", true),
    col("notes", "text", "Mapping caveats"),
  ]),
  table("fmp_industry_mappings", "Rule mapping from FMP industry into the canonical sector tree.", [
    col("id", "uuid", "Primary key", true),
    col("fmp_industry", "text", "Exact FMP industry string", true),
    col("sector_code", "text", "Target sector code", true),
    col("sub_category_slug", "text", "Target sub-category slug", true),
    col("priority", "integer", "Lower number wins when one FMP industry appears more than once", true),
    col("is_primary", "boolean", "Default mapping flag", true),
    col("notes", "text", "Why this mapping exists or why it is ambiguous"),
  ]),
  table("theme_groups", "Cross-sector investment themes such as AI, defense, policy, and momentum.", [
    col("slug", "text", "Stable theme slug, primary key", true),
    col("name", "text", "Display name", true),
    col("status", "text", "implemented or planned", true),
    col("description", "text", "Admin-facing meaning"),
    col("sort_order", "integer", "Admin display order", true),
    col("is_active", "boolean", "Visible and usable flag", true),
  ]),
  table("theme_sub_categories", "Theme child buckets with keywords and seed symbols. This is the manual/LLM guide layer that FMP industry cannot provide.", [
    col("slug", "text", "Stable sub-theme slug, primary key", true),
    col("theme_group_slug", "text", "References theme_groups.slug", true),
    col("name", "text", "Display name", true),
    col("status", "text", "implemented or planned", true),
    col("keywords", "text[]", "Trigger keywords and phrases used by parsers, LLM prompts, and trend screens", true),
    col("seed_symbols", "text[]", "Representative tickers used as a starting basket, not a hard membership list", true),
    col("description", "text", "Admin-facing meaning"),
    col("sort_order", "integer", "Admin display order", true),
    col("is_active", "boolean", "Visible and usable flag", true),
    col("metadata", "jsonb", "Source links, prompt hints, and classification notes"),
  ]),
  table("ticker_classifications", "Current ticker-to-sector/sub-category assignment. This is the sector ticker membership table, generated from FMP mappings with room for manual override.", [
    col("symbol", "text", "References tickers.symbol", true),
    col("sector_code", "text", "Current canonical sector"),
    col("sub_category_slug", "text", "Current canonical sub-category"),
    col("method", "text", "rule, llm, manual, or unknown", true),
    col("confidence", "numeric", "0 to 1 confidence"),
    col("manual_override", "boolean", "True when admin overrode the automatic result", true),
    col("reason", "text", "Short classification reason"),
    col("updated_at", "timestamptz", "Last classification update", true),
    col("metadata", "jsonb", "Rule hits, LLM trace, and source payload"),
  ]),
  table("market_group_snapshots", "Cached sector and sub-category market performance for Market tab, value maps, and top-mover lists.", [
    col("id", "uuid", "Primary key", true),
    col("scope", "text", "sector or sub_category", true),
    col("sector_code", "text", "References market_sectors.code", true),
    col("sub_category_slug", "text", "References market_sub_categories.slug when scope is sub_category"),
    col("window", "text", "1d, 5d, 1m, or 3m", true),
    col("as_of", "timestamptz", "Snapshot time", true),
    col("change_pct", "numeric", "Weighted or average percentage change for the group", true),
    col("volume", "numeric", "Aggregate or representative trading volume"),
    col("market_cap", "numeric", "Aggregate market cap for the group"),
    col("ticker_count", "integer", "Number of active symbols included", true),
    col("top_symbols", "jsonb", "Top movers in the group, e.g. [{symbol, price, change_pct, volume}]", true),
    col("source", "text", "fmp, polygon, calculated, or mixed", true),
    col("metadata", "jsonb", "Calculation method, provider payload references, and exclusions"),
  ]),
  table("ticker_theme_members", "Ticker-to-theme membership for watchlists, rankings, and market-moving views.", [
    col("symbol", "text", "References tickers.symbol", true),
    col("theme_group_slug", "text", "References theme_groups.slug", true),
    col("theme_sub_category_slug", "text", "Optional references theme_sub_categories.slug"),
    col("method", "text", "rule, llm, manual, or unknown", true),
    col("confidence", "numeric", "0 to 1 confidence"),
    col("reason", "text", "Why the ticker belongs to the theme"),
    col("updated_at", "timestamptz", "Last membership update", true),
  ]),
  table("event_theme_links", "Theme links at event level; this is separate from ticker membership.", [
    col("event_id", "uuid", "References events.id", true),
    col("theme_group_slug", "text", "References theme_groups.slug", true),
    col("theme_sub_category_slug", "text", "Optional references theme_sub_categories.slug"),
    col("method", "text", "rule, llm, manual, or unknown", true),
    col("confidence", "numeric", "0 to 1 confidence"),
    col("reason", "text", "Why this event is tied to the theme"),
    col("created_at", "timestamptz", "Creation time", true),
  ]),
  table("theme_snapshots", "Theme-level market context for Market-Moving News.", [
    col("id", "uuid", "Primary key", true),
    col("theme_group_slug", "text", "References theme_groups.slug", true),
    col("theme_sub_category_slug", "text", "Optional references theme_sub_categories.slug"),
    col("as_of", "timestamptz", "Snapshot time", true),
    col("change_pct", "numeric", "Theme or basket percentage change"),
    col("volume_score", "numeric", "Relative volume or activity score"),
    col("event_count", "integer", "Events linked to the theme in the window"),
    col("alert_count", "integer", "Alert-level events linked to the theme in the window"),
    col("top_symbols", "jsonb", "Top symbols and weights"),
    col("metadata", "jsonb", "Provider and calculation trace"),
  ], "later"),
] as const;

function map(
  sector: string,
  subCategory: string,
  slug: string,
  fmpIndustries: string[],
  notes?: string,
): SectorMapping {
  return {
    sector,
    subCategory,
    slug,
    fmpIndustries,
    notes,
  };
}

function subTheme(
  themeGroupSlug: string,
  slug: string,
  name: string,
  keywords: string[],
  seedSymbols: string[],
  description: string,
  references: Array<{ label: string; url: string }>,
  sortOrder: number,
  status: ThemeGroupStatus = "implemented",
): ThemeSubTheme {
  return {
    slug,
    themeGroupSlug,
    name,
    status,
    keywords,
    seedSymbols,
    description,
    references,
    sortOrder,
  };
}

function table(
  name: string,
  purpose: string,
  columns: Array<{ name: string; type: string; required?: boolean; notes: string }>,
  status: "required" | "later" = "required",
) {
  return {
    name,
    group: "taxonomy" as const,
    status,
    purpose,
    columns,
  };
}

function col(name: string, type: string, notes: string, required = false) {
  return {
    name,
    type,
    notes,
    required,
  };
}
